export const GET_COLLECTIONS_START = 'SHOP-REDUCER/GET_COLLECTIONS_START';
export const GET_COLLECTIONS_SUCCSES = 'SHOP-REDUCER/GET_COLLECTIONS_SUCCSES';
export const GET_COLLECTIONS_FAILED = 'SHOP-REDUCER/GET_COLLECTIONS_FAILED';
