export const GET_COLLECTIONS_START = "SHOP-REDUCER/GET_COLLECTIONS_START"
export const GET_COLLECTIONS_SUCCESS = "SHOP-REDUCER/GET_COLLECTIONS_SUCCESS"
export const GET_COLLECTIONS_FAILED = "SHOP-REDUCER/GET_COLLECTIONS_FAILED"

export const TOGGLE_LOADER = "SHOP-REDUCER/TOGGLE_LOADER"
