export const TOGGLE_CAR_HIDDEN = 'CART-REDUCER/TOGGLE_CAR_HIDDEN';
export const ADD_ITEM_TO_CART = 'CART-REDUCER/ADD_ITEM_TO_CART';
export const REMOVE_CHOOSED_ITEM_FROM_CART = 'CART-REDUCER/REMOVE_CHOOSED_ITEM_FROM_CART';
export const REDUCE_CHOOSED_VALUE_IN_ITEM = 'CART-REDUCER/REDUCE_CHOOSED_ITEM_FROM_CART';