export const SIGN_IN_WITH_GOOGLE_START =
  "USER-REDUCER/SIGN_IN_WITH_GOOGLE_START"
export const SIGN_IN_WITH_GOOGLE_SUCCESS =
  "USER-REDUCER/SIGN_IN_WITH_GOOGLE_SUCCESS"
export const SIGN_IN_WITH_GOOGLE_FAILED =
  "USER-REDUCER/SIGN_IN_WITH_GOOGLE_FAILED"

export const CHECK_USER_SESSION_START = "USER-REDUCER/CHECK_USER_SESSION_START"
export const CHECK_USER_SESSION_FAILED =
  "USER-REDUCER/CHECK_USER_SESSION_FAILED"

export const SIGN_IN_WITH_EMAIL_PASSWORD_START =
  "USER-REDUCER/SIGN_IN_WITH_EMAIL_PASSWORD_START"
export const SIGN_IN_WITH_EMAIL_PASSWORD_SUCCESS =
  "USER-REDUCER/SIGN_IN_WITH_EMAIL_PASSWORD_SUCCESS"
export const SIGN_IN_WITH_EMAIL_PASSWORD_FAILED =
  "USER-REDUCER/SIGN_IN_WITH_EMAIL_PASSWORD_FAILED"

export const SIGN_OUT_START = "USER-REDUCE/SIGN_OUT_START"
export const SIGN_OUT_SUCCESS = "USER-REDUCE/SIGN_OUT_SUCCESS"
export const SIGN_OUT_FAILED = "USER-REDUCE/SIGN_OUT_FAILED"

export const CREATE_USER_EMAIL_AND_PASSWORD_START =
  "USER-REDUCER/CREATE_USER_EMAIL_AND_PASSWORD_START"
export const CREATE_USER_EMAIL_AND_PASSWORD_SUCCESS =
  "USER-REDUCER/CREATE_USER_EMAIL_AND_PASSWORD_SUCCESS"
export const CREATE_USER_EMAIL_AND_PASSWORD_FAILED =
  "USER-REDUCER/CREATE_USER_EMAIL_AND_PASSWORD_FAILED"

export const TOGGLE_LOADER = "USER-REDUCE/TOGGLE_LOADER"
