
export const SIGN_IN_WITH_GOOGLE_START = 'USER-REDUCER/SIGN_IN_WITH_GOOGLE_START';
export const SIGN_IN_WITH_GOOGLE_SUCCSES = 'USER-REDUCER/SIGN_IN_WITH_GOOGLE_SUCCSES'
export const SIGN_IN_WITH_GOOGLE_FAILED = 'USER-REDUCER/SIGN_IN_WITH_GOOGLE_FAILED'

export const CHECK_USER_SESION_START = 'USER-REDUCER/CHECK_USER_SESION_START';
export const CHECK_USER_SESION_FAILED = 'USER-REDUCER/CHECK_USER_SESION_FAILED';

export const SIGN_IN_WITH_EMAIL_PASSWODR_START = 'USER-REDUCER/SIGN_IN_WITH_EMAIL_PASSWODR_START';
export const SIGN_IN_WITH_EMAIL_PASSWODR_SUCCSES = 'USER-REDUCER/SIGN_IN_WITH_EMAIL_PASSWODR_SUCCSES';
export const SIGN_IN_WITH_EMAIL_PASSWODR_FAILED = 'USER-REDUCER/SIGN_IN_WITH_EMAIL_PASSWODR_FAILED';

export const SIGN_OUT_START = 'USER-REDUCE/SIGN_OUT_START'
export const SIGN_OUT_SUCCSES = 'USER-REDUCE/SIGN_OUT_SUCCSES'
export const SIGN_OUT_FAILED = 'USER-REDUCE/SIGN_OUT_FAILED'

export const CREATE_USER_EMAIL_AND_PASSWORD_START = 'USER-REDUCER/CREATE_USER_EMAIL_AND_PASSWORD_START';
export const CREATE_USER_EMAIL_AND_PASSWORD_SUCCSES = 'USER-REDUCER/CREATE_USER_EMAIL_AND_PASSWORD_SUCCSES';
export const CREATE_USER_EMAIL_AND_PASSWORD_FAILED = 'USER-REDUCER/CREATE_USER_EMAIL_AND_PASSWORD_FAILED';